<?php

namespace ContainerFhpYvSt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRideBikeCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RideBikeCommand' shared autowired service.
     *
     * @return \App\Command\RideBikeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RideBikeCommand.php';

        $container->privates['App\\Command\\RideBikeCommand'] = $instance = new \App\Command\RideBikeCommand();

        $instance->setName('rideBike');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
