<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQXkWOBo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQXkWOBo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQXkWOBo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQXkWOBo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQXkWOBo\App_KernelDevDebugContainer([
    'container.build_hash' => 'QXkWOBo',
    'container.build_id' => '3e548039',
    'container.build_time' => 1704307010,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQXkWOBo');
